schema_version: 1

context:
  name: fastgit
  version: "0.0.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fastgit-${{ version }}.tar.gz
  sha256: 972e4d9e8fa2d6eee4698c0ef2dc1a39ad692f0be12279bd311a0aee6b2f4d10

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=64.0
    - pip
  run:
    - python >=${{ python_min }}
    # Not listed but needed for import
    - fastcore

tests:
  - python:
      imports:
        - fastgit
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Use git from python, fast
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/AnswerDotAI/fastgit

extra:
  recipe-maintainers:
    - thewchan
